# Adds namespace to all resources.
namespace: release-namespace

bases:
- ../local-development/tilt

patchesJson6902:
- target:
    group: admissionregistration.k8s.io
    version: v1
    kind: MutatingWebhookConfiguration
    name: patch-operator-mutating-webhook-configuration
  path: ./cert-manager-ca-injection.yaml
- target:
    group: admissionregistration.k8s.io
    version: v1
    kind: ValidatingWebhookConfiguration
    name: patch-operator-validating-webhook-configuration
  path: ./cert-manager-ca-injection.yaml