name: pull request
on:
  pull_request:
    branches:
      - master
      - main

jobs:
  shared-operator-workflow:
    name: shared-operator-workflow
    uses: redhat-cop/github-workflows-operators/.github/workflows/pr-operator.yml@2bd783cd4f843f2db2b04fe175aadea1bab5c30a
    with:
      RUN_UNIT_TESTS: true
      RUN_INTEGRATION_TESTS: false
      RUN_HELMCHART_TEST: true
